Linear Algebra Tasks

Matrix Creation and Manipulation


Create various types of matrices (zero matrix, identity matrix, random matrix).

In [6]:
import numpy as np
# Creating matrices

# Zero Matrix
zero_matrix = np.zeros((4, 4))
print("Zero Matrix:\n", zero_matrix)

# Identity Matrix
identity_matrix = np.eye(4)
print("\nIdentity Matrix:\n", identity_matrix)

# Random Matrix
random_matrix = np.random.random((4, 4))
print("\nRandom Matrix:\n", random_matrix)

Zero Matrix:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random Matrix:
 [[0.30440259 0.24230233 0.14608704 0.20106763]
 [0.08181121 0.77266051 0.21225901 0.48815156]
 [0.5902244  0.58713028 0.2914264  0.20490597]
 [0.60395792 0.71899946 0.27939434 0.83410728]]


Perform basic matrix operations (addition, subtraction, multiplication).


In [7]:
matrix_sum = zero_matrix + identity_matrix
print("Addittion Matrix\n", matrix_sum)

# Subtraction
matrix_diff = identity_matrix - random_matrix
print("Matrix Subtraction:\n", matrix_diff)

# Multiplication
matrix_product = np.dot(identity_matrix, random_matrix)
print("Matrix Multiplication:\n", matrix_product)

Addittion Matrix
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matrix Subtraction:
 [[ 0.69559741 -0.24230233 -0.14608704 -0.20106763]
 [-0.08181121  0.22733949 -0.21225901 -0.48815156]
 [-0.5902244  -0.58713028  0.7085736  -0.20490597]
 [-0.60395792 -0.71899946 -0.27939434  0.16589272]]
Matrix Multiplication:
 [[0.30440259 0.24230233 0.14608704 0.20106763]
 [0.08181121 0.77266051 0.21225901 0.48815156]
 [0.5902244  0.58713028 0.2914264  0.20490597]
 [0.60395792 0.71899946 0.27939434 0.83410728]]


Transpose a matrix and find the determinant and inverse of a matrix.

In [8]:
# Transpose
transpose_matrix = np.transpose(random_matrix)
print("\nTransposed Matrix:\n", transpose_matrix)


Transposed Matrix:
 [[0.30440259 0.08181121 0.5902244  0.60395792]
 [0.24230233 0.77266051 0.58713028 0.71899946]
 [0.14608704 0.21225901 0.2914264  0.27939434]
 [0.20106763 0.48815156 0.20490597 0.83410728]]


Solving Linear Equations

Use NumPy to solve a system of linear equations.


In [9]:
# Solving Linear Equations using NumPy

# System of equations:
# 2x + 3y = 5
# 4x + y = 6
A = np.array([[2, 3], [4, 1]])
b = np.array([5, 6])

# Solving Ax = b
solution = np.linalg.solve(A, b)
print("\nSolution to the system of equations:\n", solution)




Solution to the system of equations:
 [1.3 0.8]


Implement matrix factorization methods (LU decomposition, QR decomposition).


In [10]:
# LU Decomposition
from scipy.linalg import lu

P, L, U = lu(A)
print("\nLU Decomposition:\nP:\n", P, "\nL:\n", L, "\nU:\n", U)

# QR Decomposition
Q, R = np.linalg.qr(A)
print("\nQR Decomposition:\nQ:\n", Q, "\nR:\n", R)


LU Decomposition:
P:
 [[0. 1.]
 [1. 0.]] 
L:
 [[1.  0. ]
 [0.5 1. ]] 
U:
 [[4.  1. ]
 [0.  2.5]]

QR Decomposition:
Q:
 [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]] 
R:
 [[-4.47213595 -2.23606798]
 [ 0.         -2.23606798]]


Eigenvalues and Eigenvectors

Calculate the eigenvalues and eigenvectors of a given matrix.

Verify the results by reconstructing the original matrix.


In [11]:
# Eigenvalues and Eigenvectors

matrix = np.array([[4, -2], [1, 1]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

# Verifying the result by reconstructing the original matrix
reconstructed_matrix = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)
print("\nReconstructed Matrix:\n", reconstructed_matrix)



Eigenvalues:
 [3. 2.]

Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]

Reconstructed Matrix:
 [[ 4. -2.]
 [ 1.  1.]]


Vector Operations

Perform basic vector operations (addition, dot product, cross product).

Normalize a vector and compute vector norms.


In [12]:
# Vector Operations

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Addition
vector_sum = vector1 + vector2
print("\nVector Addition:\n", vector_sum)

# Dot Product
dot_product = np.dot(vector1, vector2)
print("\nDot Product:\n", dot_product)

# Cross Product
cross_product = np.cross(vector1, vector2)
print("\nCross Product:\n", cross_product)

# Normalization
vector_norm = np.linalg.norm(vector1)
normalized_vector = vector1 / vector_norm
print("\nNormalized Vector:\n", normalized_vector)

# Vector Norms
l1_norm = np.linalg.norm(vector1, 1)
l2_norm = np.linalg.norm(vector1, 2)
print("\nL1 Norm:\n", l1_norm)
print("\nL2 Norm:\n", l2_norm)



Vector Addition:
 [5 7 9]

Dot Product:
 32

Cross Product:
 [-3  6 -3]

Normalized Vector:
 [0.26726124 0.53452248 0.80178373]

L1 Norm:
 6.0

L2 Norm:
 3.7416573867739413


Matrix Decomposition
Understand and implement Principal Component Analysis (PCA) using SVD.


In [13]:
# Principal Component Analysis (PCA) using SVD

# Generating a random matrix
np.random.seed(0)
data_matrix = np.random.rand(5, 3)

# SVD Decomposition
U, S, Vt = np.linalg.svd(data_matrix, full_matrices=False)
print("\nSVD Decomposition:\nU:\n", U, "\nS:\n", S, "\nVt:\n", Vt)

# PCA using SVD
# Principal components are the columns of Vt
principal_components = Vt.T
print("\nPrincipal Components:\n", principal_components)



SVD Decomposition:
U:
 [[-0.45123442  0.03197382  0.25685819]
 [-0.37472871  0.3259849   0.74454664]
 [-0.56437838  0.40661144 -0.49026357]
 [-0.42559538 -0.07056365 -0.36205226]
 [-0.3953625  -0.84994084  0.0907412 ]] 
S:
 [2.39745183 0.62848817 0.28324302] 
Vt:
 [[-0.45321709 -0.70394399 -0.54686117]
 [-0.2176047  -0.5075543   0.83368868]
 [ 0.86443188 -0.49684152 -0.07685076]]

Principal Components:
 [[-0.45321709 -0.2176047   0.86443188]
 [-0.70394399 -0.5075543  -0.49684152]
 [-0.54686117  0.83368868 -0.07685076]]


Calculus

Numerical Differentiation

Use NumPy to compute the numerical derivative of a given function.

Implement forward, backward, and central difference methods for differentiation.


In [14]:
import numpy as np

# Function to differentiate
def f(x):
    return np.sin(x)

# Numerical differentiation methods
def forward_difference(f, x, h):
    return (f(x + h) - f(x)) / h

def backward_difference(f, x, h):
    return (f(x) - f(x - h)) / h

def central_difference(f, x, h):
    return (f(x + h) - f(x - h)) / (2 * h)

# Parameters
x = np.pi / 4  # Point at which to differentiate
h = 1e-5       # Small step size

# Compute derivatives
forward_diff = forward_difference(f, x, h)
backward_diff = backward_difference(f, x, h)
central_diff = central_difference(f, x, h)

print("Forward Difference:", forward_diff)
print("Backward Difference:", backward_diff)
print("Central Difference:", central_diff)


Forward Difference: 0.7071032456451575
Backward Difference: 0.7071103167000102
Central Difference: 0.7071067811725839


Numerical Integration

Use NumPy to compute the numerical integral of a given function.

Implement the trapezoidal rule and Simpson's rule for integration.


In [15]:
# Function to integrate
def f(x):
    return np.sin(x)

# Numerical integration methods
def trapezoidal_rule(f, a, b, n):
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    return (h/2) * (y[0] + 2 * np.sum(y[1:n]) + y[n])

def simpsons_rule(f, a, b, n):
    if n % 2 == 1:  # n must be even
        n += 1
    x = np.linspace(a, b, n+1)
    y = f(x)
    h = (b - a) / n
    return (h/3) * (y[0] + 4 * np.sum(y[1:n:2]) + 2 * np.sum(y[2:n-1:2]) + y[n])

# Parameters
a = 0            # Start of interval
b = np.pi        # End of interval
n = 1000         # Number of subintervals

# Compute integrals
trapezoidal_integral = trapezoidal_rule(f, a, b, n)
simpsons_integral = simpsons_rule(f, a, b, n)

print("Trapezoidal Rule:", trapezoidal_integral)
print("Simpson's Rule:", simpsons_integral)


Trapezoidal Rule: 1.9999983550656624
Simpson's Rule: 2.0000000000010827


Partial Derivatives

Calculate partial derivatives of multivariable functions using NumPy.

Verify results by comparing with analytical solutions.


In [16]:
# Multivariable function
def f(x, y):
    return x**2 + y**2

# Partial derivatives
def partial_derivative_x(f, x, y, h):
    return (f(x + h, y) - f(x, y)) / h

def partial_derivative_y(f, x, y, h):
    return (f(x, y + h) - f(x, y)) / h

# Parameters
x = 1.0
y = 1.0
h = 1e-5

# Compute partial derivatives
partial_x = partial_derivative_x(f, x, y, h)
partial_y = partial_derivative_y(f, x, y, h)

print("Partial Derivative with respect to x:", partial_x)
print("Partial Derivative with respect to y:", partial_y)

# Analytical partial derivatives
analytical_partial_x = 2 * x
analytical_partial_y = 2 * y

print("Analytical Partial Derivative with respect to x:", analytical_partial_x)
print("Analytical Partial Derivative with respect to y:", analytical_partial_y)


Partial Derivative with respect to x: 2.00001000001393
Partial Derivative with respect to y: 2.00001000001393
Analytical Partial Derivative with respect to x: 2.0
Analytical Partial Derivative with respect to y: 2.0


Optimization

Use NumPy to solve optimization problems with constraints.


In [17]:
from scipy.optimize import minimize

# Objective function
def objective(x):
    return x[0]**2 + x[1]**2

# Constraint
def constraint(x):
    return x[0] + x[1] - 1

# Initial guess
x0 = [0.5, 0.5]

# Constraints dictionary
cons = {'type': 'eq', 'fun': constraint}

# Bounds for variables
bnds = ((0, None), (0, None))

# Solve optimization problem
solution = minimize(objective, x0, method='SLSQP', bounds=bnds, constraints=cons)

print("Solution to the optimization problem:")
print("x:", solution.x)
print("Objective function value:", solution.fun)


Solution to the optimization problem:
x: [0.5 0.5]
Objective function value: 0.5
