Some more Questions

Given a 2D array, use slicing to extract every second row and every second column, then add a 1D array to each row of the sliced array.


In [17]:
import numpy as np


arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])


sliced_arr = arr[::2, ::2]
print("Sliced Array:")
print(sliced_arr)


b = np.array([1, 2])


result = sliced_arr + b
print("Resultant Array after Adding 1D array to Each Row:")
print(result)


Sliced Array:
[[ 1  3]
 [ 9 11]]
Resultant Array after Adding 1D array to Each Row:
[[ 2  5]
 [10 13]]


From a 3D array of shape (4, 3, 2), extract a sub-array using slicing and then use broadcasting to subtract a 2D array from each slice along the third axis.

In [18]:
import numpy as np

# Example 3D array of shape (4, 3, 2)
arr = np.array([
    [[1, 2], [3, 4], [5, 6]],
    [[7, 8], [9, 10], [11, 12]],
    [[13, 14], [15, 16], [17, 18]],
    [[19, 20], [21, 22], [23, 24]]
])

# Example 2D array of shape (4, 3)
b = np.array([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3],
    [4, 4, 4]
])

# Extracting the entire sub-array for this example
sub_array = arr[:, :, :]

# Subtracting the 2D array from each slice along the third axis
# We need to expand the dimensions of b to match the 3D array shape for broadcasting
result = sub_array - b[:, :, np.newaxis]

print("Original 3D Array:")
print(arr)
print("\n2D Array to Subtract:")
print(b)
print("\nResultant Array after Subtracting 2D array from Each Slice:")
print(result)


Original 3D Array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]

2D Array to Subtract:
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]

Resultant Array after Subtracting 2D array from Each Slice:
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 5  6]
  [ 7  8]
  [ 9 10]]

 [[10 11]
  [12 13]
  [14 15]]

 [[15 16]
  [17 18]
  [19 20]]]


Given a 2D array, extract the diagonal elements and create a 1D array.


In [19]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

diagonal_elements = np.diag(arr)

print("Original 2D Array:")
print(arr)
print("\nDiagonal Elements:")
print(diagonal_elements)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Diagonal Elements:
[1 5 9]


Use slicing to reverse the order of elements in each row of a 2D array.


In [20]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

reversed_rows = arr[:, ::-1]

print("Original 2D Array:")
print(arr)
print("\n2D Array with Reversed Rows:")
print(reversed_rows)


Original 2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2D Array with Reversed Rows:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


Given a 3D array of shape (4, 5, 6), use slicing to extract a sub-array of shape (2, 3, 4) and then use broadcasting to add a 1D array of shape (4,) to each row along the third axis.

In [21]:
import numpy as np


arr = np.random.rand(4, 5, 6)

sub_array = arr[:2, :3, :4]

b = np.array([1, 2, 3, 4])

b_reshaped = b.reshape(1, 1, 4)
result = sub_array + b_reshaped

print("Original 3D Array (Shape (4, 5, 6)):")
print(arr)
print("\nExtracted Sub-array (Shape (2, 3, 4)):")
print(sub_array)
print("\n1D Array to Add (Shape (4,)):")
print(b)
print("\nResultant Array after Adding 1D Array to Each Row Along the Third Axis:")
print(result)


Original 3D Array (Shape (4, 5, 6)):
[[[0.63992102 0.14335329 0.94466892 0.52184832 0.41466194 0.26455561]
  [0.77423369 0.45615033 0.56843395 0.0187898  0.6176355  0.61209572]
  [0.616934   0.94374808 0.6818203  0.3595079  0.43703195 0.6976312 ]
  [0.06022547 0.66676672 0.67063787 0.21038256 0.1289263  0.31542835]
  [0.36371077 0.57019677 0.43860151 0.98837384 0.10204481 0.20887676]]

 [[0.16130952 0.65310833 0.2532916  0.46631077 0.24442559 0.15896958]
  [0.11037514 0.65632959 0.13818295 0.19658236 0.36872517 0.82099323]
  [0.09710128 0.83794491 0.09609841 0.97645947 0.4686512  0.97676109]
  [0.60484552 0.73926358 0.03918779 0.28280696 0.12019656 0.2961402 ]
  [0.11872772 0.31798318 0.41426299 0.0641475  0.69247212 0.56660145]]

 [[0.26538949 0.52324805 0.09394051 0.5759465  0.9292962  0.31856895]
  [0.66741038 0.13179786 0.7163272  0.28940609 0.18319136 0.58651293]
  [0.02010755 0.82894003 0.00469548 0.67781654 0.27000797 0.73519402]
  [0.96218855 0.24875314 0.57615733 0.59204193 0.

Create a 2D array and use both slicing and broadcasting to set the last column to the sum of the first two columns for each row.

In [22]:
import numpy as np

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 2D Array:")
print(arr)

sum_first_two_columns = arr[:, 0] + arr[:, 1]

arr[:, -1] = sum_first_two_columns

print("\nModified 2D Array with Last Column as the Sum of the First Two Columns:")
print(arr)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified 2D Array with Last Column as the Sum of the First Two Columns:
[[ 1  2  3]
 [ 4  5  9]
 [ 7  8 15]]


serial 20


Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).


In [23]:
import numpy as np

arr = np.array([
    [ 1,  2,  3,  4,  5,  6],
    [ 7,  8,  9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36]
])

print("Original 2D Array:")
print(arr)

sub_array = arr[1:3, 1:3]

print("\nExtracted 2x2 Sub-array:")
print(sub_array)


Original 2D Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Extracted 2x2 Sub-array:
[[ 8  9]
 [14 15]]


From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.

In [24]:
import numpy as np


arr = np.array([
    [[ 1], [ 2]],
    [[ 3], [ 4]],
    [[ 5], [ 6]]
])

print("Original 3D Array:")
print(arr)


try:
    sub_array = arr[:2, :, 1]
except IndexError as e:
    print("\nError: ", e)
    sub_array = arr[:2, :, 0]

print("\nExtracted Elements (First Two Rows, Second Slice Along Third Axis):")
print(sub_array)


Original 3D Array:
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]

Error:  index 1 is out of bounds for axis 2 with size 1

Extracted Elements (First Two Rows, Second Slice Along Third Axis):
[[1 2]
 [3 4]]


Given an array of integers, use fancy indexing to extract elements at positions [1, 3, 4, 6].


In [25]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

indices = [1, 3, 4, 6]

extracted_elements = arr[indices]

print("Original Array:")
print(arr)

print("\nExtracted Elements at Positions [1, 3, 4, 6]:")
print(extracted_elements)


Original Array:
[10 20 30 40 50 60 70 80]

Extracted Elements at Positions [1, 3, 4, 6]:
[20 40 50 70]


Given a 2D array, use fancy indexing to select rows [0, 2, 2] and columns [1, 3].


In [26]:
import numpy as np

# Step 1: Create a 2D array
arr = np.array([
    [ 1,  2,  3,  4],
    [ 5,  6,  7,  8],
    [ 9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Step 2: Use fancy indexing to select rows [0, 2, 2] and columns [1, 3]
rows = np.array([0, 2, 2])
cols = np.array([1, 3])

# Fancy indexing to get the elements at the specified rows and columns
selected_elements = arr[rows[:, np.newaxis], cols]

print("Original 2D Array:")
print(arr)

print("\nSelected Elements at Rows [0, 2, 2] and Columns [1, 3]:")
print(selected_elements)


Original 2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Selected Elements at Rows [0, 2, 2] and Columns [1, 3]:
[[ 2  4]
 [10 12]
 [10 12]]


From a 1D array of random integers, extract all elements that are greater than 8.


In [27]:
import numpy as np


np.random.seed(0)
arr = np.random.randint(0, 15, size=10)

selected_elements = arr[arr > 8]

print("Original 1D Array:")
print(arr)

print("\nElements Greater Than 8:")
print(selected_elements)


Original 1D Array:
[12  5  0  3 11  3  7  9  3  5]

Elements Greater Than 8:
[12 11  9]


Given a 2D array of shape (6, 6), replace all elements greater than 13 with the value 0.


In [28]:
import numpy as np


np.random.seed(0)
arr = np.random.randint(0, 20, size=(6, 6))

print("Original 2D Array:")
print(arr)

mask = arr > 13

arr[mask] = 0

print("\nModified 2D Array (Elements > 13 replaced with 0):")
print(arr)


Original 2D Array:
[[12 15  0  3  3  7]
 [ 9 19 18  4  6 12]
 [ 1  6  7 14 17  5]
 [13  8  9 19 16 19]
 [ 5 15 15  0 18  3]
 [17 19 19 19 14  7]]

Modified 2D Array (Elements > 13 replaced with 0):
[[12  0  0  3  3  7]
 [ 9  0  0  4  6 12]
 [ 1  6  7  0  0  5]
 [13  8  9  0  0  0]
 [ 5  0  0  0  0  3]
 [ 0  0  0  0  0  7]]


Add a 1D array of shape (3,) to each row of a 2D array of shape (4, 3).


In [29]:
import numpy as np

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

arr_1d = np.array([10, 20, 30])

result = arr_2d + arr_1d

print("Original 2D Array:")
print(arr_2d)

print("\n1D Array to Add:")
print(arr_1d)

print("\nResult after Adding 1D Array to Each Row:")
print(result)


Original 2D Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

1D Array to Add:
[10 20 30]

Result after Adding 1D Array to Each Row:
[[11 22 33]
 [14 25 36]
 [17 28 39]
 [20 31 42]]


Multiply a 2D array of shape (3, 3) by a 1D array of shape (3,).


In [30]:
import numpy as np

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

arr_1d = np.array([2, 3, 4])

result = arr_2d * arr_1d

print("Original 2D Array:")
print(arr_2d)

print("\n1D Array for Multiplication:")
print(arr_1d)

print("\nResult after Multiplying 2D Array by 1D Array:")
print(result)


Original 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

1D Array for Multiplication:
[2 3 4]

Result after Multiplying 2D Array by 1D Array:
[[ 2  6 12]
 [ 8 15 24]
 [14 24 36]]


Create two 2D arrays of shapes (3, 1) and (1, 4) respectively, and perform element-wise addition.


In [31]:
import numpy as np

# Step 1: Create two 2D arrays of shapes (3, 1) and (1, 4)
arr1 = np.array([[1], [2], [3]])  # shape (3, 1)
arr2 = np.array([[10, 20, 30, 40]])  # shape (1, 4)

# Step 2: Perform element-wise addition using broadcasting
result = arr1 + arr2

print("Array 1 (shape {}):".format(arr1.shape))
print(arr1)

print("\nArray 2 (shape {}):".format(arr2.shape))
print(arr2)

print("\nResult of Element-wise Addition:")
print(result)


Array 1 (shape (3, 1)):
[[1]
 [2]
 [3]]

Array 2 (shape (1, 4)):
[[10 20 30 40]]

Result of Element-wise Addition:
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


Given a 3D array of shape (2, 3, 4), add a 2D array of shape (3, 4) to each 2D slice along the first axis.


In [32]:
import numpy as np

arr_3d = np.array([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],

    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

arr_2d = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

result = arr_3d + arr_2d[np.newaxis, :, :]

print("Original 3D Array (shape {}):".format(arr_3d.shape))
print(arr_3d)

print("\n2D Array to Add (shape {}):".format(arr_2d.shape))
print(arr_2d)

print("\nResult after Adding 2D Array to Each 2D Slice:")
print(result)


Original 3D Array (shape (2, 3, 4)):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

2D Array to Add (shape (3, 4)):
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Result after Adding 2D Array to Each 2D Slice:
[[[ 11  22  33  44]
  [ 55  66  77  88]
  [ 99 110 121 132]]

 [[ 23  34  45  56]
  [ 67  78  89 100]
  [111 122 133 144]]]
